### ISSUE TITLE
Repeat symbol gets ignored

### ISSUE THREAD

**Issue by Flova** [UHHRobotics22-23/marimbabot#262]
Nothing crashes, but the repeat sign at the end of the piece is recognized, but ignored. It is still shown in the visualization, but the robot plays the piece only once.

**Comment by Juphex** [comment]
This leads me to the assumption, that my repeat fix works (as it is displayed) but it "breaks" somewhere else, right?
@Flova

**Comment by Flova** [comment]
It might be the case that this issue occurred because #242 was not merged yet. But we should test it again.

**Comment by scaredycode** [comment]
> It might be the case that this issue occurred because #242 was not merged yet. But we should test it again.

I don't think this fixes the issue as I did not change much in the interpreter. If the interpreter still does not consider the repeat, I will just pass it a different sequence in which I manually "write out" the repeat. 
I can probably fix this tomorrow, otherwise I can only continue working on it on monday after work.

**Comment by Flova** [comment]
Okay 👍
