### ISSUE TITLE
Gazebo simulation of contact with keys

### ISSUE THREAD

**Issue by Juphex** [UHHRobotics22-23/marimbabot#41]
Gazebo simulation to simulate contact with keys & get which note was played. Requires changes to the URDF model (fixed -> prismatic joints for bars?)

**Comment by normanhendrich** [comment]
I tried out contact-sensors in Gazebo last week. The plugin is quite "expensive" in terms of CPU/network load, due to the high number of published messages. As Gazebo reports pairs of contacting objects, it might be enough to add one contact sensor to the mallet head and take the marimba bar played from the collision pair.

In case anyone wants to play with this, my contact sensor example should run out of the box: 
github.com/TAMS-Group/tams_tactile_sensor_array_gazebo
