### ISSUE TITLE
voice command recognition

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#52]

**Comment by scaredycode** [comment]
https://openai.com/research/whisper

**Comment by yunlong-wang-cn** [comment]
voice commands for system behavior. commands include

    read (update from vision once)
    play (play currently detected score)
    stop (intuitive semantics)
    repeat/loop (play current score continuously)
    concatenate (maintain a larger score and append to it from vision)
    repeat
    slower, faster, louder, softer (adapt robot parameters)
    in different scale / transposed (adapt musical parameters)

**Comment by yunlong-wang-cn** [comment]
the following commands should be recognized:

    **read** (update from vision once)
    **play** (play currently detected score)
    **stop** (intuitive semantics)
    **repeat**/loop (play current score continuously)
    **concatenate** (maintain a larger score and append to it from vision)
    **repeat**
    **slower**, **faster**, **louder**, **softer** (adapt robot parameters)

**Comment by v4hn** [comment]
for reference as a possible alternative: a colleague just set up https://github.com/alphacep/ros-vosk two weeks ago with rather good results.

**Comment by v4hn** [comment]
From https://github.com/UHHRobotics22-23/marimbabot/issues/51#issuecomment-1519122599
> Based on my understanding, the possible text-form speech examples for "shifting" could be: "C four transpose" or "C sharp", is that right?

Easy speech examples for transposition could be
- "play 3 half-tones higher/lower" (step based),
- "play a forth/fifth/octave higher/lower" (interval based)

You can also instruct performers to
- "play this melody in G major" and they would look for the base tone of the piece (your vision currently only supports C-major and a-minor because accidentals are not supported), find the interval to go from the base tone C to G and transpose by that interval (a fifth up OR a forth down). Note that you cannot transpose by an octave with such an instruction (which you need to play the upper notes of the marimba).

**Comment by yunlong-wang-cn** [comment]
Thanks for your information @v4hn
